export const CHANGE_INPUT = 'changeInput'
export const ADD_ITEM = 'addItem'
export const DELETE_ITEM = 'deleteItem'
export const INIT_LIST_ACTION = 'initListAction'
export const GET_INIT_LIST = 'getInitList'